[package]
name = "curite_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.8", features = ["derive"] }
dxr = "0.4.0"
handlebars = "4.3.4"
http = "0.2.8"
http-serde = "1.1.2"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = { version = "0.1.10", features = ["net"] }
url = { version = "2.3.1", features = ["serde"] }
warp = "0.3.3"
