server: irc.libera.chat:+6697
# '#' in nickname is replaced with a random digit
# for the usecase that the bot doesn't need to be findable
nickname: curite-#####
password: curite:hunter2
nickserv-name: nickserv@services.
httpd-port: 8080

url-success: https://example.com/v/success
url-failure: https://example.com/v/fail

# GET /account/token HTTP/1.1
# Note that these will still appear between /s, so you cannot have eg a token of this/that/other
account-re: "[^/]+"
token-re: "[^/]+"
