listen: /tmp/curite.sock
listen_perms: "660"
xmlrpc: http://[::1]:8086/xmlrpc
templates: templates/*.html

verify:
  success: https://libera.chat/registration/success
  failure: https://libera.chat/registration/failure
  target: "/curite/verify/{{account}}/{{token}}"

validation:
  account: '^[\-0-9A-Z\[\\\]^_`a-z{|}]+$'
  token: '^[0-9A-Za-z]+$'
