inbound: /tmp/curite.sock
outbound: http://[::1]:8086/xmlrpc

verify:
  template: templates/verify.html
  success: https://libera.chat/registration/success
  failure: https://libera.chat/registration/failure

validation:
  account: '^[\-0-9A-Z\[\\\]^_`a-z{|}]+$'
  token: '^[0-9A-Za-z]+$'
