server: irc.libera.chat:+6697
nickname: curite
password: curite:hunter2
nickserv-name: nickserv@services.
socket-path: /tmp/curite.sock

url-success: https://example.com/v/success
url-failure: https://example.com/v/fail

# GET /account/token HTTP/1.1
path-pattern: "^/(?P<account>[^/]+)/(?P<token>[^/]+)$"
