name: Release

on:
  create:
    tags:
      - v*

jobs:
  release:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
    name: build
    runs-on: ubuntu-latest
    container: rust:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release --target-dir /tmp
      - name: Copy assets into upload dir
        run: cp --archive --verbose templates/verify.html /tmp/${{ matrix.target }}/release/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: |
            /tmp/${{ matrix.target }}/release/curite
            /tmp/${{ matrix.target }}/release/verify.html
